from enum import Enum

class WorkflowState(Enum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_PROCESSED = "DOCUMENT_PROCESSED"
    TAX_RULES_FETCHED = "TAX_RULES_FETCHED"
    TAX_CALCULATED = "TAX_CALCULATED"
    RETURN_GENERATED = "RETURN_GENERATED"
    COMPLETED = "COMPLETED"